### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [linden-honey/linden-honey-scraper-go#2]
## TODO 
- [x] add README
- [x] improve comments in the domain package
- [ ] add doc.go to each package
- [x] add example tests

**Comment by alebabai** [comment]
outdated
